CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE users.user (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    password VARCHAR(250) DEFAULT NULL
);